version: '3.6'

services:
  telegraf:
    image: telegraf:1.18-alpine
    hostname: telegraf-1
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '8125:8125/udp'

  influxdb:
    image: influxdb:1.8-alpine
    env_file: configuration.env
    ports:
      - '8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:8.0.2
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

  mongo:
    image: mongo
    hostname: mongodb-1
    ports:
      - "27017:27017"
    env_file: configuration.env

  elasticsearch:
    image: elasticsearch:8.1.1
    hostname: elasticsearch-1
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file: configuration.env

  nginx:
    image: nginx:latest
    hostname: nginx-1
    ports:
      - "8080:80"
    env_file: configuration.env
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    image: php:8.1-fpm
    hostname: app-1
    ports:
      - "9000:9000"
    env_file: configuration.env
    volumes:
      - ./php/index.php:/var/www/html/index.php
      - ./php/status.conf:/usr/local/etc/php-fpm.d/zz-status.conf

volumes:
  grafana_data: {}
  influxdb_data: {}
